### ISSUE TITLE
provide gsettings schema

### ISSUE THREAD

**Issue by kmotavalli** [ubports/unity8-desktop-session#1]
as of now unity8 is supported on ubuntu 16.04, which comes with gnome apps preinstalled.
Unity8 should provide its own gsettings schema to better integrate with gnome apps, such as the file manager, nautilus, which spuns up 2 windows: its UI and a desktop window for desktop support.

this, and other papercuts, could be dealt with providing a new schema (workaround: gsettings set org.gnome.desktop.background show-desktop-icons false)

**Comment by dobey** [comment]
What does this mean exactly? Unity8 does install its own settings schema. You are suggesting it should change the settings in other apps as well? That seems inappropriate.

Probably Nautilus should be hidden from the menu under Unity8, but the .desktop file would need updated for this.

**Comment by dobey** [comment]
Closing due to lack of response, and being filed in wrong repo.
